### PR TITLE
Fixes to pass lesson check

### PR DESCRIPTION
**Pull request by colinsauze**
* Using the latest bin directory and Makefile from the lesson template.
* Replacing python with language-python in code examples
* Removing some FIXME statements
* Renumbering episodes so there aren't two numbered 05
* Other misc fixes to pass lesson check

### CODE REVIEW

**Comment by colinsauze** [comment]
I don't understand why this isn't passing the checks. It runs make lesson-check fine on my computer.

**Review by vinisalazar — APPROVED** [review]
This is a big one, but I checked out the branch on my local environment and the lesson seems to be building fine. Looks good to me.

Thank you @colinsauze.

**Comment by colinsauze** [comment]
Its now telling me all checks have passed, but says its skipping the test lesson template check. I really don't understand why its skipped it and if that means it still isn't working right.

**Comment by maxim-belkin** [comment]
> I really don't understand why its skipped it and if that means it still isn't working right.

it is working as intended. Template check is performed in the carpentries/styles repo only.

**Pull request merged**
